[package]
name = "JGLauncher"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
jni = { version = "0.19" , features = ["invocation"]}
ring = "0.17.8"
clap = "4.5"
zip = "2.2"
sha2 = "0.10"
hex = "0.4"
rvmti="0.3.0"
#file-lock = "2.1"

[build-dependencies]
#sha2 = "0.10"
#hex = "0.4"