[package]
name = "JGLauncher"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
jni = { version = "0.21" , features = ["invocation"]}
ring = "0.17.8"
clap = "4.5"
zip = "2.2"
sha2 = "0.10"
hex = "0.4"
rvmti= { path = "lib/rvmti" }
#file-lock = "2.1"

[build-dependencies]
rand="0.8.5"
#sha2 = "0.10"
#hex = "0.4"